"""Generate paper/table_alignment.tex from results/results.json.

Every probed layer of every model is included (no row selection); the
redundant ResNet `avgpool` probe is dropped because it is identical to
GAP(layer4) by construction (stated in the caption).
"""
import json
from pathlib import Path

HERE = Path(__file__).parent
RESULTS = HERE.parent / "results" / "results.json"
OUT = HERE / "table_alignment.tex"

BLOCKS = [
    ("vgg16",           "VGG-16 (trained)"),
    ("resnet18",        "ResNet-18 (trained)"),
    ("vgg16_random",    "VGG-16 (random)"),
    ("resnet18_random", "ResNet-18 (random)"),
]
SKIP_LAYERS = {"avgpool"}


def fmt(v, nd=3):
    return f"{v:.{nd}f}" if isinstance(v, (int, float)) else "--"


def fmt_ratio(v):
    return f"{v:.1f}$\\times$" if isinstance(v, (int, float)) else "--"


def main():
    with open(RESULTS) as f:
        data = json.load(f)

    lines = [
        "% Auto-generated by gen_table.py — do not edit by hand.",
        "\\begin{tabular}{llrrrrrr}",
        "\\toprule",
        "Network & Layer & $d$ & ID & $\\kcos$ & ratio & split-half & "
        "within$\\times$split \\\\",
        "\\midrule",
    ]

    for bi, (key, label) in enumerate(BLOCKS):
        model = data.get(key)
        if not model:
            continue
        if bi > 0:
            lines.append("\\midrule")
        first = True
        for lname, m in model["layers"].items():
            if lname in SKIP_LAYERS:
                continue
            net = label if first else ""
            first = False
            id_s = (f"{m['twonn_id']:.1f}$\\pm${m.get('twonn_id_std', 0):.1f}"
                    if isinstance(m.get("twonn_id"), float) else "--")
            lines.append(
                f"{net} & {lname} & {m['embed_dim']} & {id_s} & "
                f"{fmt(m.get('mean_cos2'))} & {fmt_ratio(m.get('ratio'))} & "
                f"{fmt_ratio(m.get('split_half_ratio'))} & "
                f"{fmt_ratio(m.get('within_split_ratio'))} \\\\"
            )

    lines += ["\\bottomrule", "\\end{tabular}"]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
